export const exercises = [
  {
    id: 1,
    title: 'Quick Death',
    slug: 'quick-death',
    tags: ['warmups', 'intensity'],
    timeLength: 2,
    bpm: 200,
    timesCompleted: 4,
  },
  {
    id: 2,
    title: 'Pre-show Ritual',
    slug: 'pre-show-ritual',
    tags: ['warmups'],
    timeLength: 10,
    bpm: 175,
    timesCompleted: 4,
  },
  {
    id: 3,
    title: 'A Clean Fifteen',
    slug: 'clean-fifteen',
    tags: ['warmups'],
    timeLength: 15,
    bpm: 120,
    timesCompleted: 5,
  },
  {
    id: 4,
    title: 'Quick & Thirty',
    slug: 'quick-and-thirty',
    tags: ['warmups'],
    timeLength: 10,
    bpm: 140,
    timesCompleted: 0,
  },
  {
    id: 5,
    title: 'Slow & Steady',
    slug: 'slow-and-steady',
    tags: ['endurance'],
    timeLength: 30,
    bpm: 135,
    timesCompleted: 0,
  },
  {
    id: 6,
    title: '60 for 60',
    slug: '60-for-60',
    tags: ['endurance'],
    timeLength: 60,
    bpm: 60,
    timesCompleted: 0,
  },
  {
    id: 7,
    title: 'Up, Up & Away',
    slug: 'up-up-away',
    tags: ['intensity'],
    timeLength: 45,
    bpm: [150, 250],
    timesCompleted: 0,
  },
  {
    id: 8,
    title: 'Forearm Burn',
    slug: 'forearm-burn',
    tags: ['endurance', 'intensity'],
    timeLength: 15,
    bpm: 190,
    timesCompleted: 0,
  },
  {
    id: 9,
    title: 'Slow Death',
    slug: 'slow-death',
    tags: ['endurance', 'intensity'],
    timeLength: 15,
    bpm: 200,
    timesCompleted: 4,
  },
]